### ISSUE TITLE
Plans for Sentry's new Python SDK

### ISSUE THREAD

**Issue by jezdez** [NicolasLM/spinach#1]
I was wondering if you thought about adding an integration for [Sentry's new Python SDK](https://github.com/getsentry/sentry-python) instead of the Raven support? Some more infos can be found in [their docs](https://docs.sentry.io/platforms/python/).

There are a few example integrations already ([Celery](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/celery.py), [RQ](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/rq.py)) that could be used as an example maybe?

**Comment by NicolasLM** [comment]
This is definitely something that will need to be done. I was waiting for the dust to settle a bit, the last time I checked the new SDK it was pretty much a work in progress.

**Comment by jezdez** [comment]
Right the composition based design of the integrations API is interesting but I'm not sure how well this would fit into the patterns of the signals Spinach provides. E.g. individual signals for the various states of the workers and jobs makes sense for user code but may not be enough to oversee the whole stack when running the workers.
