### ISSUE TITLE
Newest redis-py causes ImportErrors

### ISSUE THREAD

**Issue by 0xDEC0DE** [NicolasLM/spinach#12]
Release 4.1.0 of redis-py appears to have introduced a silent breaking change:

https://github.com/redis/redis-py/pull/1751

This causes Spinach to fail to load the Redis broker.

# Steps to reproduce

```
tox -r
```

# Expected result

Tests pass

# Actual behaviour

Tests fail with `ImportError` exceptions

**Comment by NicolasLM** [comment]
Closed by #13.
