### ISSUE TITLE
Queued jobs are not exposed on the API until you get a signal about them

### ISSUE THREAD

**Issue by juledwar** [NicolasLM/spinach#21]
The `engine.schedule` and `schedule_at` methods always return None. It would be much handier if they returned the Jobs that were queued, so they can be more easily matched with signals that happen later. This then fills in a gap where a job might be queued and want to see how long it took before it was started.

**Comment by bigjools** [comment]
@NicolasLM I'd like to get a release out with the last 2 fixes, are you OK with that? Happy to do it if you don't have time. Might need you to confirm your preferred way to do that as I messed it up last time and had to do it twice!

**Comment by NicolasLM** [comment]
@bigjools I did the release, I'm sure the process could be improved a bit but it's quite simple:

- Create and push to master a new commit "Release version X.X.X" that bumps the version in `const.py`.
- Use this commit to create a release via the GitHub UI.

**Comment by bigjools** [comment]
That's great, thanks!

You might be able to use `setuptools_scm` for auto-versioning, I can propose a change at a later date. It means you can just make a tag and push the tag instead.
