### ISSUE TITLE
Flask >= 2.2 breaks the Spinach extension

### ISSUE THREAD

**Issue by juledwar** [NicolasLM/spinach#24]
Flask's context stack has been deprecated in favour of a Python ContextVar and all use of push/pop/top on the context stack is also deprecated.

Flask is maintaining a fake stack over the top of the ContextVar, however this seems to break Spinach. I'm not sure why yet but it may be because there's actually only one value, not a stack, and using a pop will unset the context completely.

**Comment by juledwar** [comment]
I have a fix in flight; it should work for old and new Flask.

**Comment by 0xDEC0DE** [comment]
We will also need another Spinach release to properly make use of this.

**Comment by NicolasLM** [comment]
@0xDEC0DE Done.

**Comment by bigjools** [comment]
Thanks for the quick release @NicolasLM !
