### ISSUE TITLE
Can't call start_workers more than once

### ISSUE THREAD

**Issue by juledwar** [NicolasLM/spinach#7]
I want to have worker threads for different queues all running in the same process. To do this I did something like:

```
engine.start_workers(number=1, block=False)
engine.start_workers(number=1, queue='my-special-queue', block=False)
```

However the second call is rejected with `RuntimeError('Workers are already running')`

Is this something that I can fix or is it entirely intentional to block further workers on different queues for some reason I can't see?

**Comment by juledwar** [comment]
It looks like I should just create a new Engine per queue type with the current code.

**Comment by juledwar** [comment]
Also, given that I am using the flask_spinach extension this doesn't look particularly straightforward!

**Comment by NicolasLM** [comment]
Yes, not being able to call start_workers multiple times on the same engine is intentional. The engine holds a reference to one pool of workers.

As you figured, using bare Spinach it is possible to create two brokers and two engines in the same process but the Flask/Spinach integration assumes one Flask app has one Spinach engine, so it will be tough.

**Comment by juledwar** [comment]
Perhaps we could allow mixing of queue names in the initial call? Although from eyeballing the code that seems rather difficult also as all the `Workers` share the same queue name.

**Comment by NicolasLM** [comment]
Closing this one as the design is intentional. Feel free to open another issue to discuss improving the flexibility of queues, if needed.

**Comment by juledwar** [comment]
That's fair. I did work around it by avoiding the existing Flask extension, which I think is where someone should look first if they want to fix this.
